---
- name: Ping localhost
  hosts: 
    - workstations
  tasks:
    - name: Ping test
      ansible.builtin.ping:
  roles:
    - ansible-role-backup
    - ansible-role-zsh
    #- ansible-role-workstation

